version: "2"
run:
  tests: false
linters:
  default: all
  disable:
    - copyloopvar
    - depguard
    - err113
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - gochecknoglobals
    - gochecknoinits
    - intrange
    - ireturn
    - nlreturn
    - revive
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl
    - noinlineerr
  settings:
    cyclop:
      max-complexity: 12
    godox:
      keywords:
        - HACK
        - FIXME
        - BUG
  exclusions:
    generated: lax
    rules:
      - linters:
          - gosec
        text: 'G306:'
      - linters:
          - gosec
        text: 'G301:'
      - linters:
          - lll
        path: ssml
      - linters:
          - cyclop
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
