dist: focal

language: go
go:
  - "1.16.x"
  - "1.x"
env:
  global:
    - GO111MODULE=on
    - GOARCH=amd64
    - GOOS=linux
    - GOLANGCI_LINTER_VERSION=v1.42.0
    - CGO_ENABLED=1
    # COVERALLS_TOKEN

before_script:
  - go mod download
  - go get github.com/mattn/goveralls
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin $GOLANGCI_LINTER_VERSION

script:
  - golangci-lint run
  - go vet ./...
  - go test -race -gcflags=-l -covermode=count -coverprofile=profile.cov ./...
  - goveralls -coverprofile=profile.cov -service=travis-ci
