dist: focal

language: go
go:
  - "1.16.x"
  - "1.x"
env:
  global:
    - GO111MODULE=on
    - GOARCH=amd64
    - GOOS=linux
    - GOLANGCI_LINTER_VERSION=v1.44.0
    - CGO_ENABLED=1
    # COVERALLS_TOKEN

before_script:
  - go mod download
  - go get github.com/mattn/goveralls
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin $GOLANGCI_LINTER_VERSION

script:
  - golangci-lint run
  - go vet ./...
  - go test -race -gcflags=-l ./...
  - go test -gcflags=-l -covermode=count -coverprofile=profile.cov ./...
  - goveralls -coverprofile=profile.cov -service=travis-ci
